---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен иметь русскую и английскую версию 
  - При переключении с одной языковой версии на другую, должна пересчитываться валюта
  - На сайте должна присутствовать форма регистрации пользователей
  - На сайте должна быть размещена информация о компании, предоставляющей услуги
  - На сайте должен присутствовать договор-оферта
  - На сайте должна быть размещена информация об условиях оплаты, гарантии, доставки и возврате товаров
  - На сайте должна быть размещена информация с контактами продавца (форма связи, номер телефона)
